name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Message that will be displayed on users'' first issue'
        pr-message: 'Message that will be displayed on users'' first pr'
The Alluminaire a non profit organization to help people help people.. We are accepting donations and holding findraisers to provide sercret services to those in need seeking out and restoring ethics to humanity created for good people by good people to build more good people
